title: Chengyin 
description: USC MS Business Analytics Graduate 
author: Chengyin Liu 
image: https://drive.google.com/file/d/1XuMcPQzmCyPDbRyV5QWW71odi8knzobc/view?usp=sharing
theme: jekyll-theme-midnight 
