title: Chengyin 
description: USC MS Business Analytics Graduate 
author: Chengyin Liu 
image: https://images.unsplash.com/photo-1504639725590-34d0984388bd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1867&q=80
theme: jekyll-theme-midnight 
